### ISSUE TITLE
Tribes GitHub Action

### ISSUE THREAD

**Issue by tomsmith8** [stakwork/sphinx-tribes#2724]
## Trigger /sync on Master Updates

- [ ]  Configure the GitHub Action to watch for updates on both frontend and backend master branches.
- [ ]  On update, call the Swarm /sync endpoint with a `pat` params and 
GET https://boltwll.swarm38.sphinx.chat/api/git/sync?source_link=https://github.com/stakwork/sphinx-tribes,https://github.com/stakwork/sphinx-tribes-frontend
- [ ]  Include `pat` parameter in the request

```
name: Stakgraph - Sync Codebase
on:
  push:
    branches:
      - master
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Call Swarm Sync Endpoint
        run: |
          curl -G "https://boltwall.swarm38.sphinx.chat/api/git/sync" \
            --header "x-api-token: ${{ secrets.SWARM_API_KEY }}" \
            --data-urlencode "source_link=https://github.com/stakwork/sphinx-tribes,https://github.com/stakwork/sphinx-tribes-frontend" \
            --data-urlencode "pat=${{ secrets.TRIBES_GITHUB_PAT }}"
```

@stakwork

[CodespaceURL](https://bookish-zebra-9795jgj5q4jwhx59x.github.dev/)
